### ISSUE TITLE
[FR] Support for inline table editing - similar to Prisma Studio

### ISSUE THREAD

**Issue by zaini** [clidey/whodb#12]
Rather than having to write SQL to edit my tables, I'd like to be able to edit the tables inline.

I'm coming from [Prisma Studio](https://www.prisma.io/studio) so that should give you an idea of the experience there, which is overall very good.

One major issue I had with Prisma Studio though is that it doesn't seem to support adding new lines for String columns when editing inline :((

Also doesn't support a markdown editor, because sometimes I store MD in my String columns

**Comment by hkdeman** [comment]
For sure! Inline editing is the next up feature. We are trying to enhance it where the experience to edit and "preview" (on click hold) is quite good. I love the markdown editor (even for preview). Will keep this thread updated :)

**Comment by hkdeman** [comment]
Inline actions are released! https://github.com/clidey/whodb/pull/17

Further, now you can hold a cell and preview its value. This supports JSON & Markdown! Hopefully it is useful! Do let us know any feedback.
