### ISSUE TITLE
[FR] Filters based on the table

### ISSUE THREAD

**Issue by zaini** [clidey/whodb#13]
Rather than having to write a `WHERE` SQL filter, I'd like to just have some UI to create simple filters based on the table I am viewing.

Prisma Studio has something like that:

![image](https://github.com/clidey/whodb/assets/51179189/33084646-6bb7-4519-8cff-9c2fb15ae94f)

**Comment by hkdeman** [comment]
Thank you for the suggestion! We will prioritize with the team as it is a very useful feature and hopefully get back to this soon! Will update :)
