### ISSUE TITLE
local hostname?

### ISSUE THREAD

**Issue by kqvanity** [clidey/whodb#135]
Whenever i try to connect to my local mariadb server, I get the following error
```bash
2024/09/04 06:39:18 /app/src/plugins/mysql/db.go:18
[error] failed to initialize database, got error dial tcp: lookup keinvanity on 192.168.1.1:53: no such host
2024/09/04 06:39:18 [4b7cfb109319/Y7H6E3cmdf-000007] "POST http://0.0.0.0:8080/api/query HTTP/1.1" from 172.17.0.1:50146 - 200 68B in 10.037262311s
```

**Comment by hkdeman** [comment]
Hello there! 

Just to understand the problem statement better, are you trying to access the MariaDB that is also in another docker container?

Based on the error, it looks like you are trying to access "keinvanity" hostname. Could you share more details on the docker network you are using? If you are exposing the MariaDB in localhost - you could also use "host.docker.internal" to connect to your host's local network.

**Comment by kqvanity** [comment]
>  are you trying to access the MariaDB that is also in another docker container?

It's locally installed. I tried providing my local machine hostname, but it raises this error!

**Comment by kqvanity** [comment]
I basically followed [this](https://stackoverflow.com/questions/67454473/failed-to-initialize-database-got-error-dial-tcp-127-0-0-13306-connect-conne) solution, and got it working on my linux host
