### ISSUE TITLE
[BUG] mysql connection use "mysql" db by default

### ISSUE THREAD

**Issue by anthosz** [clidey/whodb#139]
Hello,

Thanks to the docker ENV that works as expected!

If we apply this env (or even if submit via the form):
WHODB_MYSQL_1: "{\"host\":\"mysql\",\"user\":\"user\",\"database\":\"test\"}"

Once connected, it's the "mysql" schema that is opened instead "test" db like specified in the conf.

Best regards,

**Comment by hkdeman** [comment]
Thank you for pointing out the bug! Will update the thread when we have the fix out :)
