### ISSUE TITLE
[FR] Adding env to customize the base path

### ISSUE THREAD

**Issue by anthosz** [clidey/whodb#140]
Hello,

At this time, whodb use the root path "/". Do you think it's possible to personalize that?

The idea is to simplify the workflow when we have a single hostname to be able to reverse proxy each path of each app to his own application.

Best regards,

**Comment by hkdeman** [comment]
Thank you for the suggestion! Definitely something that would be important. Let me see how we can prioritize this!

**Comment by hkdeman** [comment]
Hey, thank you for waiting!

We have fixed this in the latest PR: https://github.com/clidey/whodb/pull/195

This should be the same as all Advanced configuration!

Once, the build is complete, it should be available on DockerHub :)

Build Status: &nbsp; <img src="https://hello.clidey.com/api/flows/status?id=b32257fa-1415-4847-a0f3-e684f5f76608&secret=cd74dbd5-36ec-42f9-b4f0-12ce9fcc762b" alt="Clidey build status" height="20px" />
