### ISSUE TITLE
Ability to change Redis database

### ISSUE THREAD

**Issue by foresturquhart** [clidey/whodb#151]
It would be really valuable to have the ability to change between the different Redis databases. This could use the same UX as the SQL databases, with the dropdown below the Profile dropdown.

**Comment by hkdeman** [comment]
Thank you for the suggestion!

It is slightly hard with Redis as you would still require the ports to be mentioned (like when logging in).

Is this for organizing multiple databases under one Redis login profiles?

**Comment by foresturquhart** [comment]
I mean multiple databases under one Redis login profile, yes. We often have to switch between databases 7 and 8 for example, and it would be great to be able to access those both with a quick dropdown.

**Comment by hkdeman** [comment]
Oh I understand! Will add this to our backlog and update here soon! :)

**Comment by foresturquhart** [comment]
Thank you!

**Comment by hkdeman** [comment]
Thank you for waiting!

We have fixed this in the latest PR: https://github.com/clidey/whodb/pull/188

Once, the build is complete, it should be available on DockerHub :)

Build Status: &nbsp; <img src="https://hello.clidey.com/api/flows/status?id=b32257fa-1415-4847-a0f3-e684f5f76608&secret=cd74dbd5-36ec-42f9-b4f0-12ce9fcc762b" alt="Clidey build status" height="20px" />

**Comment by hkdeman** [comment]
Closing this issue but feel free to open this up if you face any issues @foresturquhart!
