### ISSUE TITLE
[FR] To support Clear Text Password login for Google Cloud SQL IAM Authentication

### ISSUE THREAD

**Issue by raymond-xu-gtg** [clidey/whodb#168]
Hi team, 

I like WhoDB and I tried it with my Google Cloud SQL MySQL instance. It works however since I use Cloud SQL IAM Auth, the client needs to support `clear text password`. 

Error log
```
2024/09/23 04:26:14 /app/src/plugins/mysql/db.go:18
[error] failed to initialize database, got error this user requires clear text authentication. If you still want to use it, please add 'allowCleartextPasswords=1' to your DSN
```

Ref. 
- https://cloud.google.com/sql/docs/mysql/iam-logins#logging-in-as-a-user
- https://dev.mysql.com/doc/refman/8.4/en/cleartext-pluggable-authentication.html

Cheers
Ray

**Comment by hkdeman** [comment]
Hey!

Thank you for choosing WhoDB! Great to see the FR :)

We have extended the MySQL config in this PR: https://github.com/clidey/whodb/pull/173

CI/CD Build Status: &nbsp; <img src="https://hello.clidey.com/api/flows/status?id=b32257fa-1415-4847-a0f3-e684f5f76608&secret=cd74dbd5-36ec-42f9-b4f0-12ce9fcc762b" alt="Clidey build status" height="20px" />

Once, complete the new version should be available on the DockerHub.

**Comment by raymond-xu-gtg** [comment]
Thanks @hkdeman for your quick response! I'll give it a try.

**Comment by raymond-xu-gtg** [comment]
Sorry for the late response. The switch looks good however I need SSL support to test this properly as SSL is enforced for Google IAM users. I'll write up another FR.
