### ISSUE TITLE
Unable to use sqlite

### ISSUE THREAD

**Issue by ocrumbs** [clidey/whodb#199]
Hi,

Thanks for the project, I built this locally and run the binary directly without docker, to be able to use it with sqlite. However, I am getting this error.

![Screenshot from 2024-10-05 16-25-01](https://github.com/user-attachments/assets/7faa6aa6-acb5-43d0-bef1-ed694a31d9e1)

Thanks again!

**Comment by hkdeman** [comment]
Hey! There is a small bug you found here - when running locally - it actually checks for a __tmp__ folder inside the _core_ folder (our backend). If you put your sqlite3 database there - you should be able to find it in this dropdown.

I would recommend using docker/docker-compose - the experience is significantly better and plus you can easily mount the file to __/db/__ without altering/linking the file in which it is being used.

**Comment by ocrumbs** [comment]
Thanks for the quick response, I now have **tmp** folder in place but still facing the same issue. Do you think the issue may be related to the **unauthorized** graphql response from the server (among other things)  preventing from moving further?

I cannot use docker because I will need to eventually run on a machine with no docker installation :unamused:

Thanks !

**Comment by hkdeman** [comment]
That's unusual. Let me check this out and get back on this thread.

**Comment by hkdeman** [comment]
Thank you so much for waiting! We have realized this bug was caused due to change in the schema. We have resolved this and will be releasing next! https://github.com/clidey/whodb/pull/224

**Comment by hkdeman** [comment]
This is great! Glad it works now. Would love any feedback, suggestions, and use cases that we can improve on.

**Comment by ocrumbs** [comment]
:pray: :pray:  

Thanks a ton, works very well now .
