### ISSUE TITLE
[FR] Automatically parse database URL when pasting

### ISSUE THREAD

**Issue by zaini** [clidey/whodb#200]
When I paste my DB URL like `postgresql://johndoe:randompassword@localhost:5432/mydb?schema=public` I'd like it to be parsed  and autofill the login form:

![image](https://github.com/user-attachments/assets/a8b949e8-e9c3-4f7e-b2b0-ed1b56f68518)

Example packages that do this:

* https://www.npmjs.com/package/ts-parse-database-url
* https://www.npmjs.com/package/parse-db-uri

**Comment by hkdeman** [comment]
Hello! Great suggestion!

We already do this for mongodb and definitely worth adding to Postgres. Adding this to our backlog. Thank you :)

**Comment by vr-varad** [comment]
hey @hkdeman I would like to work on this issue

**Comment by hkdeman** [comment]
Hey! That is great to hear. Pull up a PR and we are happy to check it out!

**Comment by HarshDodiya1** [comment]
Hi @hkdeman ,

I’ve addressed the issue and submitted a PR. As per your suggestion, I checked the mentioned two libraries for parsing fields from the URL, but I found that the existing logic was sufficient and didn’t require any additional dependencies.

Please review the changes and let me know if there’s anything else that needed. I’m happy to contribute more!

**Comment by hkdeman** [comment]
Thank you for the contribution! @modelorona has left a quick comment on it. Let us know your thoughts :)
