### ISSUE TITLE
want access from another port at client host  but  '-p custom-port:8080' not work, it always litening on 8080 and tips to access from '0.0.0.0:8080' 

### ISSUE THREAD

**Issue by langlichong** [clidey/whodb#212]

**Comment by hkdeman** [comment]
Hello hello! When using docker-compose you should be able to change the listening port in the client by setting "-p 8081:8080".

For example: 
<img width="1708" alt="image" src="https://github.com/user-attachments/assets/4c7e0b0f-4a7f-44fe-8f57-452b2f780c9f">

You can further alter the port by using "PORT" environment variable

For example: 
<img width="1682" alt="image" src="https://github.com/user-attachments/assets/55309ee7-67f2-4b98-8295-b31fcd5a0cae">

You should be able to access at 0.0.0.0:8080 in both the cases.

Hope this helps!

**Comment by langlichong** [comment]
@hkdeman  i tried ,  the container start with another port but 8080, but can not access the app from the tips 
![image](https://github.com/user-attachments/assets/7e4bfa39-4477-414e-ba7d-4119ad1c8a5b)

my docker container is at a ubuntu server host with inner ip 192.168.54.9 , and after mapping the prot to non-default 8080 , the containner successful, but when i access from my work desktop with http://192.168.54.9:9977 , there is no response :

**Comment by hkdeman** [comment]
The team just tried to replicate this but was unsuccessful. WhoDB server seems to be accessible throughout the local network (same WiFi connection). Happy to get on a call and try finding the issue - https://calendly.com/clidey/whodb.

This gives us a good idea to create a community channel to chat around this. Will also try setting one :)

**Comment by hkdeman** [comment]
We went on the call but unfortunately nobody joined. We will close this for now. Happy for you to open it with new information :)
