### ISSUE TITLE
no output when sql execute

### ISSUE THREAD

**Issue by wonb168** [clidey/whodb#225]
I connected to a postgres,
then run:
```
select 1
```
but where is the result to display?
![image](https://github.com/user-attachments/assets/e72c2881-d96f-4a78-8370-f1b62606811f)

**Comment by hkdeman** [comment]
Hola! Thank you for using WhoDB. We have fixed this bug in the latest release: https://github.com/clidey/whodb/releases/tag/0.42.0

When the build finishes on Clidey (<img src="https://hello.clidey.com/api/flows/status?id=b32257fa-1415-4847-a0f3-e684f5f76608&secret=cd74dbd5-36ec-42f9-b4f0-12ce9fcc762b" alt="Clidey build status" height="20px" />) you should be able to see the same version on DockerHub and pull it.

**Comment by wonb168** [comment]
and I download mac version , but how to run? my mac is M1
![image](https://github.com/user-attachments/assets/6294ddee-c6f1-40b2-8e39-7fab031300f3)

**Comment by hkdeman** [comment]
This is something we are currently trying to resolve on our end. The executables are yet to be verified and would be easier to run. Will update this thread as soon as we have this out! Thank you for waiting :)

**Comment by hkdeman** [comment]
I will close the bug for now. Will update when the executables are ready!
