### ISSUE TITLE
With a large schema, I get: Unable to query. Try again. bufio.Scanner: token too long

### ISSUE THREAD

**Issue by viovanov** [clidey/whodb#231]
I have a pretty large schema, and when I try to use Houdini with ollama (`llama3.2:latest`), I get that error.

I found this https://github.com/ollama/ollama/issues/687#issuecomment-1745678880, might be relevant?

**Comment by hkdeman** [comment]
Thank you for pointing this out! Could you please the error?

**Comment by viovanov** [comment]
@hkdeman this is the error

```
Try again. bufio.Scanner: token too long
```

**Comment by viovanov** [comment]
![image](https://github.com/user-attachments/assets/aefcabe6-c9d7-4863-8fe6-88589f7f38b5)

![image](https://github.com/user-attachments/assets/4557ea42-a599-46d0-be15-27a6ae66270e)

**Comment by viovanov** [comment]
@hkdeman anything else I can do to help debugging?

**Comment by viovanov** [comment]
awesome, thanks @hkdeman!

**Comment by viovanov** [comment]
it's working now, thanks @hkdeman !
