### ISSUE TITLE
[FR] Allow to configure creds/servers in docker env

### ISSUE THREAD

**Issue by anthosz** [clidey/whodb#32]
Hello,

In the dev/ example, we have a docker compose that contain few creds to spawn some services for tests. (mysql, etc)

What can be interesting is to allow to set the creds directly in docker env (so instead to set creds in url or type it manually, reconfigure it on docker level)

Some ideas (standalone instance):
Ex: WHODB_MYSQL_HOST, etc
or something like for multi instance: WHODB_MYSQL='{instance1={"host"="host","user"="root"}}'
WHODB_MONGO='{instance={"host"="host","auth"=false}'

**Comment by modelorona** [comment]
+1 this would be very handy to have

**Comment by hkdeman** [comment]
Great suggestion! We will try to see how to create a great UX around this and to see if it is scalable to all the databases easily. Will keep this thread updated soon!

**Comment by anthosz** [comment]
> Great suggestion! We will try to see how to create a great UX around this and to see if it is scalable to all the databases easily. Will keep this thread updated soon!

Thank you! I cannot really help on go but if you need someone to do some tests, don't hesitate :)

**Comment by hkdeman** [comment]
@anthosz Finally got the changes to this in: https://github.com/clidey/whodb/pull/69

Would love to get the feedback if you get a chance to test! Also, the docs can be found here: https://github.com/clidey/whodb/blob/main/docs/docs.md

**Comment by anthosz** [comment]
> @anthosz Finally got the changes to this in: #69
> 
> Would love to get the feedback if you get a chance to test! Also, the docs can be found here: https://github.com/clidey/whodb/blob/main/docs/docs.md

Thank you very much! Will back to you in few weeks :)

**Comment by hkdeman** [comment]
Try anytime! Will close the issue for now. Happy for you to open if you require anything.

**Comment by anthosz** [comment]
Confirmed, all ok with redis & mysql

Unable to use postgresql but not related to env
