### ISSUE TITLE
[FR] Custom port for db connection

### ISSUE THREAD

**Issue by aliefee** [clidey/whodb#35]
Login form only asks for the 'hostname' of the connection endpoint. This limits the capability of the app.

For example if someone wants to wants to connect to a Mysql database on host 0.0.0.0 the program assumes it is on 0.0.0.0:3306

**Comment by hkdeman** [comment]
Definitely a capability to add! Fix this up in the PR: https://github.com/clidey/whodb/pull/38

**Comment by hkdeman** [comment]
We have merged the PR! This should be allowed with "Advanced" tab in the bottom of the login!
