### ISSUE TITLE
[FR] Allow redis with no password

### ISSUE THREAD

**Issue by lee98064** [clidey/whodb#36]
Hello,

I hope can add support for redis without password!

Thank you for this project that seems really promising!

<img width="363" alt="image" src="https://github.com/clidey/whodb/assets/46412433/3f2191c9-b987-4d96-ac8d-66e6afb54587">

**Comment by hkdeman** [comment]
Thank you!

For sure - the fix is coming up in this PR: https://github.com/clidey/whodb/pull/38

**Comment by hkdeman** [comment]
We have merged the PR - do let us know if there is any problems you face :) Hope it helps!
