### ISSUE TITLE
[FR] Connect to MongoDB via Connection String (URI)

### ISSUE THREAD

**Issue by docryte** [clidey/whodb#37]
Sometimes it even faster and easier to connect to MongoDB via using **Connection String (URI)** like on image below.
![image](https://github.com/clidey/whodb/assets/34625468/40e1954f-0d87-4e78-9ecc-8de210ab3a45)

P.S.: It's also would be great to implement all connection settings allowed by Mongo Compass.

**Comment by hkdeman** [comment]
Great suggestion! Definitely going to make it easier to add connection string. 

To make the UX simpler, if you pasted in the "hostname" or any other field the connection string and it automatically picked up everything. Would that experience be good as well?

**Comment by hkdeman** [comment]
With this PR: https://github.com/clidey/whodb/pull/50, you should easily be able to paste the URL in the hostname and it will auto populate all of the details in the form - ready to be connected! Let me know if you are able to test it :)
