### ISSUE TITLE
Required DB names

### ISSUE THREAD

**Issue by kerray** [clidey/whodb#39]
Hi, 
Would it be possible to NOT require a DB name when connecting to MySQL/Postgres with credentials that can access several databases and just let the user pick the one to use after connecting? This would go a long way for me to use as Adminer replacement.
Thanks for considering it!

**Comment by hkdeman** [comment]
Ooo what a great suggestion!

I personally hate doing that in adminer as well. I think a single database initially would be required but let me see if we could allow switching easily in the login profile.

Will keep this thread updated as we go!

**Comment by hkdeman** [comment]
Thank you for waiting! We have released the feature request in this PR: https://github.com/clidey/whodb/pull/71

Would love the feedback if you get a chance to try.

**Comment by kerray** [comment]
I will, thanks!
