### ISSUE TITLE
Cached/old value showing after an inline edit?

### ISSUE THREAD

**Issue by h0t1ce** [clidey/whodb#43]
If I use the inline editor to change a value it will show the popup that it successfully changed the value however the table still shows the old value. Even if I navigate away and back to the same table the old value still appears. 

A manual query is needed to see the updated value.

**Comment by hkdeman** [comment]
Thank you for pointing the bug out!

We will be fixing this right away!

**Comment by hkdeman** [comment]
This should be fixed in this PR: https://github.com/clidey/whodb/pull/48. Let me know if you get a chance to try!

**Comment by h0t1ce** [comment]
Seems to work fine now. 

Thanks!
