### ISSUE TITLE
Left side of data table gets cut off if its width is larger than the window width

### ISSUE THREAD

**Issue by h0t1ce** [clidey/whodb#44]
![image](https://github.com/user-attachments/assets/822efd84-2378-45b3-8653-ba62ec0e7b9b)

Even when collapsing the left menu doesn't help

**Comment by hkdeman** [comment]
Thank you for pointing this bug out!

Fixing this right away. We will also try making the collapsed experience better in smaller screens.

**Comment by hkdeman** [comment]
This should be fixed in this PR: https://github.com/clidey/whodb/pull/48. Let me know if you get a chance to try!

**Comment by h0t1ce** [comment]
The problem is no longer there.

Thanks for the fix
