### ISSUE TITLE
Schema dropdown list is not updated on connection profile switch

### ISSUE THREAD

**Issue by h0t1ce** [clidey/whodb#51]
![image](https://github.com/user-attachments/assets/61b4ba4e-a275-4463-bb06-27f202604c50)

In the image I tried switch to another MySQL server but noticed that the schema list shows the databases from the previous connection profile. The one I switched to has over 10 databases but we can see I only have 4.

**Comment by hkdeman** [comment]
Thank you for pointing this out! Let me try reproducing this and will get back to you with a fix!

**Comment by hkdeman** [comment]
This should be fixed in the current release: https://github.com/clidey/whodb/pull/71

Thank you for pointing it out! Feel free to reopen if you face this issue.
