### ISSUE TITLE
Demo does not work

### ISSUE THREAD

**Issue by mrleblanc101** [clidey/whodb#57]
https://whodb.clidey.com/demo/login?host=quick-container-491288b0-3138-48fa-93b4-1e730296c0b7.hello.svc.cluster.local&username=user&password=password&database=Adventureworks

![Screenshot 2024-07-18 at 5 30 13 PM](https://github.com/user-attachments/assets/a10d2aad-a85c-40b2-8039-e1611998dd30)

**Comment by Cajuteq** [comment]
Hi, not related to this project at all but I was able to try a demo using the link from https://whodb.clidey.com/demo and filling the fields using the url args from the faulty link. 

I don't know how long those are up, but mine is https://qc-dde11d46-3af6-4db0-8ae6-cb33fb653871.hello.clidey.com/graph

**Comment by hkdeman** [comment]
Thank you for pointing this out!

This was indeed an issue and we fixed this now :) Hope the demo is useful!

Thank you @Cajuteq for the workaround!

**Comment by hkdeman** [comment]
This should be fixed now!
