### ISSUE TITLE
Could not capture the image 

### ISSUE THREAD

**Issue by Cajuteq** [clidey/whodb#59]
Hi, using the graph function to capture image works when there are few tables (although the quality of the screenshot makes it kinda unusable) but the function stops functionning at all when using a bigger schema.

![image](https://github.com/user-attachments/assets/6f3e8522-2b37-472c-bba4-2a0849f0da95)

![image](https://github.com/user-attachments/assets/58f6192b-5d9a-4ba5-9ddd-c30b6f6afd65)

**Comment by hkdeman** [comment]
Great observation! Checking this bug out soon. We will also try making the screenshots higher resolution if possible as well or add an easy way to delete unnecessary nodes to make the screen more compact. I believe currently "Delete" button should work after selection. Of course, this is a way to have less nodes on the screen but if the use case is to have everything then we definitely need to make the image higher resolution.
