### ISSUE TITLE
PostgreSQL update query breaks when table name is in a format like AdminId

### ISSUE THREAD

**Issue by modelorona** [clidey/whodb#60]
Hi there, I was playing around and found an issue where if I try to update a cell, it breaks with the error: 

**keeps failing that a column doesn't exist when it looks like it does**

I looked a bit through the code and I believe this is the culprit
https://github.com/clidey/whodb/blob/0fc14149581b7f886e7b56cc9eaf0c6a8c73e2db/core/src/plugins/postgres/update.go#L60
![image](https://github.com/user-attachments/assets/bfe2a6c1-27ee-4ba8-8ab8-ff4f8e520db9)

It looks like it should instead be:
```go
dbConditions = dbConditions.Where(fmt.Sprintf("\"%s\" = ?", key), value)
```

so that the column name is surrounded by quotes as well to accommodate.

I didn't have time to fully test but after making this change locally, it was working.

I did not check for the other SQL databases but if they're doing something similar, I imagine a similar issue will exist.

**Comment by hkdeman** [comment]
Oo that is a tiny detail missed! Fixing this right away. Thank you for going through the codebase and suggesting the issue!

**Comment by modelorona** [comment]
this should be fine now with pull request https://github.com/clidey/whodb/pull/73

closing
