### ISSUE TITLE
UI bugs - transparent filter selection in dark mode and Total Count: Unknown

### ISSUE THREAD

**Issue by modelorona** [clidey/whodb#61]
Hi me again, I found some UI bugs:

* In dark mode, when selecting filters, the background is transparent and it makes it hard to read
![image](https://github.com/user-attachments/assets/eed3b6dc-4f2a-4132-afdb-04329480504c)

* In various places I see Total Count: Unknown when it comes to counting the table data.

**Comment by hkdeman** [comment]
Aah the backdrop blur does not seem to work. Definitely an issue with UX! Fixing this right away.

Also, the Total Count was mentioned in other places (someone mentioned it was because of Views) - checking both of these and getting back!

**Comment by hkdeman** [comment]
The fix for backdrop is out on this PR: https://github.com/clidey/whodb/pull/64

The issue seems to be related to Chrome not supporting nested backdrop filters so we created a work around.

The unknown bug is coming soon as well!

**Comment by modelorona** [comment]
I'll close this since I see the unknown bug is present in another separate ticket. thanks for fixing the backdrop issue!
