### ISSUE TITLE
[FR] Automatically open the UI when the program is launched instead of having to do it manually.

### ISSUE THREAD

**Issue by frettini** [clidey/whodb#95]
Hello, 
Would it be possible to open localhost:8080 automatically in the browser when the program is ready? At first I wasn't sure what was meant to happen, and only after did I see the console telling me where to go. That would be great feature to have :smile: 
Thanks

**Comment by hkdeman** [comment]
Thank you for the awesome suggestion!

We have added that here: https://github.com/clidey/whodb/pull/97

Unfortunately, opening in the docker isn't easily doable. This will be working for running WhoDB locally or via our executables in our website https://whodb.clidey.com
